version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
    iptv_admin:
        build:
            context: ./
            dockerfile: Dockerfile
        image: iptv_admin
        container_name: iptv_admin
        depends_on:
            - mongodb
        command: ./server.py
        ports:
            - 8080:8080
    iptv:
        build: https://github.com/fastogt/fastocloud.git
        container_name: fastocloud
        ports:
            - 6317:6317
            - 8000:8000
            - 7000:7000
            - 6000:6000
    nginx:
        image: nginx
        container_name: nginx
        depends_on:
            - iptv_admin
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
